import type { Language } from '../../types';

export const overviewCopy = {
  en: {
    appearance: 'Appearance',
    language: 'Language',
    currency: 'Currency',
    appLock: 'App Lock',
    storage: 'Storage & Media',
    backup: 'Backup & Restore',
    reviewSetup: 'Review setup',
    reviewSetupSub: 'Review the setup steps without deleting your data.',
    terms: 'Terms of Use',
    privacy: 'Privacy Policy',
    clearData: 'Clear App Data',
    enabled: 'Enabled',
    disabled: 'Disabled',
    back: 'Back',
    appLockSub: 'PIN and auto-lock',
    storageSub: 'Media library, storage and integrity',
    backupSub: 'Backup, restore and CSV export',
    setupConfirmTitle: 'Run setup again?',
    setupConfirmMessage: 'You can review the setup steps again. Your existing expenses and settings will not be deleted.',
    continue: 'Continue',
    cancel: 'Cancel',
    version: 'Version',
    build: 'Build',
    photos: 'photos',
    storagePageSub: 'Private SpendWise photo storage and integrity.',
    backupPageSub: 'Create portable backups, restore data, or export CSV.',
    appLockPageSub: 'Control PIN protection and automatic locking.',
    mediaLibrary: 'Media Library',
    mediaLibrarySub: 'Browse, inspect and export attached photos.',
    photoStorage: 'Photo storage',
    integrity: 'Integrity',
    healthy: 'Healthy',
    issues: 'issues',
    dataOnly: 'Backup v2 · Data only',
    dataOnlySub: 'Ledger and settings without photo binaries.',
    fullBackup: 'Backup v2 · Data + photos',
    fullBackupSub: 'Portable ZIP with ledger and private attachment photos.',
    legacy: 'Legacy Backup v1 JSON',
    imported: 'Backup v2 restored',
    expenses: 'expenses',
    exportFailed: 'Export failed.',
    backupExportFailed: 'Backup export failed.',
    csvExportFailed: 'CSV export failed.',
    invalidBackup: 'Invalid or unsupported backup file.',
    importFailed: 'Import failed.',
    currencyMismatch: 'This backup uses a different currency. Merge is blocked to prevent amounts from being relabeled incorrectly.',
    currencyMismatchReplace: 'This backup uses a different currency. Merge is blocked to prevent amounts from being relabeled incorrectly. Use Replace only if you intend to restore the backup currency and all backup data.',
    backupRestoreFailed: 'Backup restore failed. Your current data was kept whenever rollback was possible.',
    backupWarning: 'Backup restored, but some old media could not be cleaned up automatically.',
    dismissMessage: 'Dismiss message',
    dismissError: 'Dismiss error',
  },
  fr: {
    appearance: 'Apparence',
    language: 'Langue',
    currency: 'Devise',
    appLock: 'Verrouillage',
    storage: 'Stockage et médias',
    backup: 'Sauvegarde et restauration',
    reviewSetup: 'Revoir la configuration',
    reviewSetupSub: 'Revoyez les étapes sans supprimer vos données.',
    terms: 'Conditions d’utilisation',
    privacy: 'Politique de confidentialité',
    clearData: 'Effacer les données de l’application',
    enabled: 'Activé',
    disabled: 'Désactivé',
    back: 'Retour',
    appLockSub: 'Code PIN et verrouillage automatique',
    storageSub: 'Médiathèque, stockage et intégrité',
    backupSub: 'Sauvegarde, restauration et export CSV',
    setupConfirmTitle: 'Revoir la configuration ?',
    setupConfirmMessage: 'Vous pouvez revoir les étapes de configuration. Vos dépenses et réglages existants ne seront pas supprimés.',
    continue: 'Continuer',
    cancel: 'Annuler',
    version: 'Version',
    build: 'Build',
    photos: 'photos',
    storagePageSub: 'Stockage privé des photos SpendWise et intégrité.',
    backupPageSub: 'Créez des sauvegardes, restaurez des données ou exportez un CSV.',
    appLockPageSub: 'Gérez le code PIN et le verrouillage automatique.',
    mediaLibrary: 'Médiathèque',
    mediaLibrarySub: 'Parcourir, vérifier et exporter les photos jointes.',
    photoStorage: 'Stockage photos',
    integrity: 'Intégrité',
    healthy: 'Correcte',
    issues: 'problèmes',
    dataOnly: 'Backup v2 · Données seules',
    dataOnlySub: 'Registre et réglages sans fichiers photo.',
    fullBackup: 'Backup v2 · Données + photos',
    fullBackupSub: 'ZIP portable avec registre et photos privées.',
    legacy: 'Backup v1 JSON hérité',
    imported: 'Backup v2 restauré',
    expenses: 'dépenses',
    exportFailed: 'Échec de l’export.',
    backupExportFailed: 'Échec de l’export de la sauvegarde.',
    csvExportFailed: 'Échec de l’export CSV.',
    invalidBackup: 'Fichier de sauvegarde invalide ou non pris en charge.',
    importFailed: 'Échec de l’import.',
    currencyMismatch: 'Cette sauvegarde utilise une autre devise. La fusion est bloquée pour éviter de réétiqueter incorrectement les montants.',
    currencyMismatchReplace: 'Cette sauvegarde utilise une autre devise. La fusion est bloquée pour éviter de réétiqueter incorrectement les montants. Utilisez Remplacer uniquement si vous voulez restaurer la devise et toutes les données de la sauvegarde.',
    backupRestoreFailed: 'Échec de la restauration. Vos données actuelles ont été conservées chaque fois qu’un retour arrière était possible.',
    backupWarning: 'La sauvegarde a été restaurée, mais certains anciens médias n’ont pas pu être nettoyés automatiquement.',
    dismissMessage: 'Fermer le message',
    dismissError: 'Fermer l’erreur',
  },
  ar: {
    appearance: 'المظهر',
    language: 'اللغة',
    currency: 'العملة',
    appLock: 'قفل التطبيق',
    storage: 'التخزين والوسائط',
    backup: 'النسخ الاحتياطي والاستعادة',
    reviewSetup: 'مراجعة الإعداد',
    reviewSetupSub: 'راجع خطوات الإعداد من دون حذف بياناتك.',
    terms: 'شروط الاستخدام',
    privacy: 'سياسة الخصوصية',
    clearData: 'مسح بيانات التطبيق',
    enabled: 'مفعّل',
    disabled: 'معطّل',
    back: 'رجوع',
    appLockSub: 'رمز PIN والقفل التلقائي',
    storageSub: 'مكتبة الوسائط والتخزين والسلامة',
    backupSub: 'النسخ والاستعادة وتصدير CSV',
    setupConfirmTitle: 'تشغيل الإعداد مرة أخرى؟',
    setupConfirmMessage: 'يمكنك مراجعة خطوات الإعداد مرة أخرى. لن يتم حذف المصاريف أو الإعدادات الحالية.',
    continue: 'متابعة',
    cancel: 'إلغاء',
    version: 'الإصدار',
    build: 'البنية',
    photos: 'صور',
    storagePageSub: 'تخزين صور SpendWise الخاصة وفحص سلامتها.',
    backupPageSub: 'أنشئ نسخاً احتياطية أو استعد البيانات أو صدّر CSV.',
    appLockPageSub: 'تحكم برمز PIN والقفل التلقائي.',
    mediaLibrary: 'مكتبة الوسائط',
    mediaLibrarySub: 'استعراض الصور المرفقة وفحصها وتصديرها.',
    photoStorage: 'مساحة الصور',
    integrity: 'السلامة',
    healthy: 'سليمة',
    issues: 'مشكلات',
    dataOnly: 'النسخة v2 · بيانات فقط',
    dataOnlySub: 'السجل والإعدادات بدون ملفات الصور.',
    fullBackup: 'النسخة v2 · بيانات + صور',
    fullBackupSub: 'ملف ZIP محمول يتضمن السجل والصور الخاصة.',
    legacy: 'نسخة v1 JSON القديمة',
    imported: 'تمت استعادة النسخة v2',
    expenses: 'مصاريف',
    exportFailed: 'فشل التصدير.',
    backupExportFailed: 'فشل تصدير النسخة الاحتياطية.',
    csvExportFailed: 'فشل تصدير CSV.',
    invalidBackup: 'ملف النسخة الاحتياطية غير صالح أو غير مدعوم.',
    importFailed: 'فشل الاستيراد.',
    currencyMismatch: 'تستخدم هذه النسخة الاحتياطية عملة مختلفة. تم منع الدمج لتجنب تغيير تسمية المبالغ بشكل غير صحيح.',
    currencyMismatchReplace: 'تستخدم هذه النسخة الاحتياطية عملة مختلفة. تم منع الدمج لتجنب تغيير تسمية المبالغ بشكل غير صحيح. استخدم الاستبدال فقط إذا كنت تريد استعادة عملة النسخة وجميع بياناتها.',
    backupRestoreFailed: 'فشلت الاستعادة. تم الاحتفاظ ببياناتك الحالية كلما كان التراجع ممكناً.',
    backupWarning: 'تمت استعادة النسخة الاحتياطية، لكن تعذر تنظيف بعض الوسائط القديمة تلقائياً.',
    dismissMessage: 'إغلاق الرسالة',
    dismissError: 'إغلاق الخطأ',
  },
} as const;


export type SettingsOverviewCopy = (typeof overviewCopy)[Language];
